/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import QNRTPlayer from 'react-native-qnrt-player';

export default class App extends Component {
  state = {
    status: 'starting',
    message: '--'
  };

  componentDidMount() {
  }

  render() {
    return (
      <View style={styles.container}>
        <QNRTPlayer style={{width: 300, height: 300}}
                    source={{uri: "http://pili-live-hls.kakayuedu.com/twmh-pili/doll_machine_1.m3u8", mHttpPost: true}}
                    onPlayerStateChanged={(e) => {
                      e.persist()
                      console.log("onPlayerStateChangede", e);
                    }}
                    onPlayerInfo={(e) => {
                      e.persist()
                      console.log("onPlayerInfo", e);
                    }}
                    onPlayerError={(e) => {
                      e.persist()
                      console.log("onPlayerError", e);
                    }}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'red'
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
